# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20160927_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='name',
            field=models.CharField(default='Unnamed', max_length=128),
        ),
    ]
