# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_paste_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='duration',
        ),
        migrations.AddField(
            model_name='paste',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 20, 33, 20, 199917)),
        ),
    ]
