# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_auto_20160927_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 0, 17, 55, 92061)),
        ),
        migrations.AlterField(
            model_name='paste',
            name='language',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
