# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_auto_20160928_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 14, 9, 6, 48213)),
        ),
    ]
